apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
  namespace: aks
spec:
  virtualhost:
    fqdn: where-for-dinner.aks.run.tap.az.ra.tapsme.org
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-where-for-dinner
      port: 80
